#!/usr/bin/env python

import sys
import dcdr.data as dt
import dcdr.load.xmlspec as xmlspec
import dcdr.output.xmlout as xmlout

spec = sys.argv[1]
if len(sys.argv) == 3:
    binary = file(sys.argv[2], 'rb').read()
else:
    binary = sys.stdin.read()

decoder = xmlspec.Importer().load(file(spec, 'r'))

data = dt.Data(binary)
xmlout.to_file(decoder, data, sys.stdout)

undecoded = str(data)
if len(undecoded) > 0:
    sys.stderr.write('%i bytes undecoded!\n' % len(undecoded))
