#!/usr/bin/env python

import sys
import bdec
import bdec.data as dt
import bdec.spec.xmlspec as xmlspec
import bdec.output.xmlout as xmlout

spec = sys.argv[1]
if len(sys.argv) == 3:
    binary = file(sys.argv[2], 'rb').read()
else:
    binary = sys.stdin.read()

decoder = xmlspec.load(file(spec, 'r'))

data = dt.Data(binary)
try:
    xmlout.to_file(decoder, data, sys.stdout)
except bdec.DecodeError, ex:
    sys.exit(str(ex))

undecoded = str(data)
if len(undecoded) > 0:
    sys.stderr.write('%i bytes undecoded!\n' % len(undecoded))
