#!/usr/bin/env python

import sys
import bdec
import bdec.data as dt
import bdec.spec.xmlspec as xmlspec
import bdec.output.xmlout as xmlout

spec = sys.argv[1]
protocol = xmlspec.load(file(spec, 'r'))

if len(sys.argv) == 3:
    xml = file(sys.argv[2], 'rb').read()
else:
    xml = sys.stdin.read()

data = xmlout.encode(protocol, xml)
try:
    binary = str(reduce(lambda a,b:a+b, data))
except bdec.DecodeError, ex:
    sys.exit(str(ex))
sys.stdout.write(binary)
