#!/usr/bin/env python

import activegrid.tool.ide

if __name__ == "__main__":
    app = activegrid.tool.ide.IDEApplication(redirect = False)
    app.GetTopWindow().Raise()  # sometimes it shows up beneath other windows.  e.g. running self in debugger
    app.MainLoop()
