#!/usr/bin/env python

from tools.bgui.tool.ide import IDEApplication

if __name__ == "__main__":
    app = IDEApplication(redirect = False)
    app.GetTopWindow().Raise()  # sometimes it shows up beneath other windows.  e.g. running self in debugger
    app.MainLoop()
